# MySQL Database Connection

spring.datasource.url=jdbc:mysql://localhost:3306/student_db

server.port=8081

spring.datasource.username=root

spring.datasource.password=${DB_PASSWORD}

# Hibernate Settings

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false

spring.thymeleaf.render-hidden-markers-before-tag-closing=true